### ISSUE TITLE
random sampling points from points cloud by _sample_point transform returns doubled points

### ISSUE THREAD

**Issue by roma-goodok** [goodok/fastai_sparse#8]
https://github.com/goodok/fastai_sparse/blob/master/fastai_sparse/transforms/main.py#L195

It looks like that random selection in _sample_point transform is implemented with replacement. Think it's better to use
`numpy.random.choice` with `replace=`**`False`**

**Comment by goodok** [comment]
Fixed in commit
https://github.com/goodok/fastai_sparse/commit/7fa2c3f025cd85c1a718f371d56d6da22d29e6bd
and published in 0.0.5 version

Now it is optional but the old behavioure remains by default  'replace=True' (this  default value may be changed in the future to the False ? )
